import type { RoutingConfig } from "./types.js";

export const DEFAULT_NVIDIA_ROUTING_CONFIG: RoutingConfig = {
  scoring: {
    tokenCountThresholds: { simple: 50, complex: 500 },

    // Multilingual keywords: EN + ZH + JA + RU + DE + ES + PT + KO + AR
    codeKeywords: [
      // English
      "function",
      "class",
      "import",
      "def",
      "select",
      "async",
      "await",
      "const",
      "let",
      "var",
      "return",
      "typescript",
      "javascript",
      "python",
      "rust",
      "sql",
      "regex",
      "stack trace",
      "bug",
      "debug",
      "exception",
      "compile",
      "refactor",
      "unit test",
      "dockerfile",
      "yaml",
      "json schema",
      "proxy",
      "middleware",
      "endpoint",
      "api",
      "```",
      // Chinese
      "函数",
      "类",
      "导入",
      "定义",
      "查询",
      "异步",
      "等待",
      "常量",
      "变量",
      "返回",
      "调试",
      "错误",
      "异常",
      "重构",
      "单元测试",
      "接口",
      // Japanese
      "関数",
      "クラス",
      "インポート",
      "非同期",
      "定数",
      "変数",
      "デバッグ",
      "例外",
      "リファクタ",
      "ユニットテスト",
      "エンドポイント",
      // Russian
      "функция",
      "класс",
      "импорт",
      "определ",
      "запрос",
      "асинхрон",
      "ожидать",
      "константа",
      "переменная",
      "вернуть",
      "отладка",
      "ошибка",
      "исключение",
      "рефакторинг",
      "юнит тест",
      // German
      "funktion",
      "klasse",
      "importieren",
      "definieren",
      "abfrage",
      "asynchron",
      "erwarten",
      "konstante",
      "variable",
      "zurückgeben",
      "debug",
      "fehler",
      "ausnahme",
      "refactoring",
      "unit test",
      // Spanish
      "función",
      "clase",
      "importar",
      "definir",
      "consulta",
      "asíncrono",
      "esperar",
      "constante",
      "variable",
      "retornar",
      "depurar",
      "error",
      "excepción",
      "refactorizar",
      "prueba unitaria",
      // Portuguese
      "função",
      "classe",
      "importar",
      "definir",
      "consulta",
      "assíncrono",
      "aguardar",
      "constante",
      "variável",
      "retornar",
      "depurar",
      "erro",
      "exceção",
      "refatorar",
      "teste unitário",
      // Korean
      "함수",
      "클래스",
      "가져오기",
      "정의",
      "쿼리",
      "비동기",
      "대기",
      "상수",
      "변수",
      "반환",
      "디버그",
      "오류",
      "예외",
      "리팩터링",
      "단위 테스트",
      // Arabic
      "دالة",
      "فئة",
      "استيراد",
      "تعريف",
      "استعلام",
      "غير متزامن",
      "انتظار",
      "ثابت",
      "متغير",
      "إرجاع",
      "تصحيح",
      "خطأ",
      "استثناء",
      "إعادة هيكلة",
      "اختبار وحدات"
    ],

    reasoningKeywords: [
      // English
      "prove",
      "theorem",
      "derive",
      "step by step",
      "chain of thought",
      "formally",
      "mathematical",
      "proof",
      "logically",
      "counterexample",
      "invariant",
      "tradeoff",
      "root cause",
      "analyze deeply",
      // Chinese
      "证明",
      "定理",
      "推导",
      "逐步",
      "思维链",
      "形式化",
      "数学",
      "逻辑",
      "反例",
      "不变量",
      "权衡",
      "根因",
      // Japanese
      "証明",
      "定理",
      "導出",
      "ステップバイステップ",
      "論理的",
      "反例",
      "不変条件",
      "トレードオフ",
      "根本原因",
      // Russian
      "доказать",
      "докажи",
      "доказательств",
      "теорема",
      "вывести",
      "шаг за шагом",
      "пошагово",
      "поэтапно",
      "цепочка рассуждений",
      "рассуждени",
      "формально",
      "математически",
      "логически",
      "контрпример",
      "инвариант",
      "компромисс",
      "первопричина",
      // German
      "beweisen",
      "beweis",
      "theorem",
      "ableiten",
      "schritt für schritt",
      "gedankenkette",
      "formal",
      "mathematisch",
      "logisch",
      "gegenbeispiel",
      "invariante",
      "abwägung",
      "ursache",
      // Spanish
      "demostrar",
      "teorema",
      "derivar",
      "paso a paso",
      "cadena de pensamiento",
      "formalmente",
      "matemático",
      "prueba",
      "lógicamente",
      "contraejemplo",
      "invariante",
      "tradeoff",
      "causa raíz",
      // Portuguese
      "provar",
      "teorema",
      "derivar",
      "passo a passo",
      "cadeia de pensamento",
      "formalmente",
      "matemático",
      "prova",
      "logicamente",
      "contraexemplo",
      "invariante",
      "trade-off",
      "causa raiz",
      // Korean
      "증명",
      "정리",
      "도출",
      "단계별",
      "사고의 연쇄",
      "형식적",
      "수학적",
      "논리적",
      "반례",
      "불변식",
      "트레이드오프",
      "근본 원인",
      // Arabic
      "إثبات",
      "نظرية",
      "اشتقاق",
      "خطوة بخطوة",
      "سلسلة التفكير",
      "رسمياً",
      "رياضي",
      "برهان",
      "منطقياً",
      "مثال مضاد",
      "ثابت",
      "مقايضة",
      "السبب الجذري"
    ],

    simpleKeywords: [
      // English
      "what is",
      "define",
      "translate",
      "hello",
      "yes or no",
      "capital of",
      "how old",
      "who is",
      "when was",
      "explain simply",
      // Chinese
      "什么是",
      "定义",
      "翻译",
      "你好",
      "是否",
      "首都",
      "多大",
      "谁是",
      "何时",
      "简单解释",
      // Japanese
      "とは",
      "定義",
      "翻訳",
      "こんにちは",
      "はいかいいえ",
      "首都",
      "誰",
      "いつ",
      "簡単に説明",
      // Russian
      "что такое",
      "определение",
      "перевести",
      "переведи",
      "привет",
      "да или нет",
      "столица",
      "сколько лет",
      "кто такой",
      "когда",
      "объясни",
      "объясни просто",
      // German
      "was ist",
      "definiere",
      "übersetze",
      "hallo",
      "ja oder nein",
      "hauptstadt",
      "wie alt",
      "wer ist",
      "wann",
      "erkläre",
      "einfach erklären",
      // Spanish
      "qué es",
      "definir",
      "traducir",
      "hola",
      "sí o no",
      "capital de",
      "cuántos años",
      "quién es",
      "cuándo",
      "explica simple",
      // Portuguese
      "o que é",
      "definir",
      "traduzir",
      "olá",
      "sim ou não",
      "capital de",
      "quantos anos",
      "quem é",
      "quando",
      "explique simples",
      // Korean
      "무엇",
      "정의",
      "번역",
      "안녕하세요",
      "예 또는 아니오",
      "수도",
      "누구",
      "언제",
      "간단히 설명",
      // Arabic
      "ما هو",
      "تعريف",
      "ترجم",
      "مرحبا",
      "نعم أو لا",
      "عاصمة",
      "من هو",
      "متى",
      "اشرح ببساطة"
    ],

    technicalKeywords: [
      // English
      "algorithm",
      "optimize",
      "architecture",
      "distributed",
      "kubernetes",
      "microservice",
      "database",
      "infrastructure",
      "gateway",
      "router",
      "schema",
      "oauth",
      "grpc",
      "latency",
      "throughput",
      "cache",
      "worker",
      "context window",
      "tool calling",
      // Chinese
      "算法",
      "优化",
      "架构",
      "分布式",
      "微服务",
      "数据库",
      "基础设施",
      "网关",
      "路由",
      "模式",
      "延迟",
      "吞吐量",
      "缓存",
      "上下文窗口",
      "工具调用",
      // Japanese
      "アルゴリズム",
      "最適化",
      "アーキテクチャ",
      "分散",
      "マイクロサービス",
      "データベース",
      "ゲートウェイ",
      "ルーター",
      "スキーマ",
      "レイテンシ",
      "スループット",
      "キャッシュ",
      // Russian
      "алгоритм",
      "оптимизировать",
      "оптимизаци",
      "оптимизируй",
      "архитектура",
      "распределённый",
      "микросервис",
      "база данных",
      "инфраструктура",
      "шлюз",
      "роутер",
      "схема",
      "латентность",
      "пропускная способность",
      "кэш",
      "контекстное окно",
      "вызов инструментов",
      // German
      "algorithmus",
      "optimieren",
      "architektur",
      "verteilt",
      "kubernetes",
      "mikroservice",
      "datenbank",
      "infrastruktur",
      "gateway",
      "router",
      "schema",
      "latenz",
      "durchsatz",
      "cache",
      // Spanish
      "algoritmo",
      "optimizar",
      "arquitectura",
      "distribuido",
      "microservicio",
      "base de datos",
      "infraestructura",
      "gateway",
      "router",
      "esquema",
      "latencia",
      "rendimiento",
      "caché",
      // Portuguese
      "algoritmo",
      "otimizar",
      "arquitetura",
      "distribuído",
      "microsserviço",
      "banco de dados",
      "infraestrutura",
      "gateway",
      "roteador",
      "esquema",
      "latência",
      "throughput",
      "cache",
      // Korean
      "알고리즘",
      "최적화",
      "아키텍처",
      "분산",
      "마이크로서비스",
      "데이터베이스",
      "인프라",
      "게이트웨이",
      "라우터",
      "스키마",
      "지연 시간",
      "처리량",
      "캐시",
      "컨텍스트 윈도우",
      "도구 호출",
      // Arabic
      "خوارزمية",
      "تحسين",
      "بنية",
      "موزع",
      "خدمة مصغرة",
      "قاعدة بيانات",
      "بنية تحتية",
      "بوابة",
      "موجه",
      "مخطط",
      "زمن الوصول",
      "الإنتاجية",
      "ذاكرة التخزين المؤقت",
      "نافذة السياق",
      "استدعاء الأدوات"
    ],

    creativeKeywords: [
      // English
      "story",
      "poem",
      "compose",
      "brainstorm",
      "creative",
      "imagine",
      "write a",
      "tagline",
      "slogan",
      // Chinese
      "故事",
      "诗",
      "创作",
      "头脑风暴",
      "创意",
      "想象",
      "写一个",
      "标语",
      // Japanese
      "物語",
      "詩",
      "作曲",
      "ブレインストーム",
      "創造的",
      "想像",
      "スローガン",
      // Russian
      "история",
      "рассказ",
      "стихотворение",
      "сочинить",
      "сочини",
      "мозговой штурм",
      "творческий",
      "представить",
      "придумай",
      "напиши",
      "слоган",
      // German
      "geschichte",
      "gedicht",
      "komponieren",
      "brainstorming",
      "kreativ",
      "vorstellen",
      "schreibe",
      "erzählung",
      "slogan",
      // Spanish
      "historia",
      "poema",
      "componer",
      "lluvia de ideas",
      "creativo",
      "imaginar",
      "escribe",
      "eslogan",
      // Portuguese
      "história",
      "poema",
      "compor",
      "criativo",
      "imaginar",
      "escreva",
      "slogan",
      // Korean
      "이야기",
      "시",
      "작곡",
      "브레인스토밍",
      "창의적",
      "상상",
      "작성",
      "슬로건",
      // Arabic
      "قصة",
      "قصيدة",
      "تأليف",
      "عصف ذهني",
      "إبداعي",
      "تخيل",
      "اكتب",
      "شعار"
    ],

    imperativeVerbs: [
      // English
      "build",
      "create",
      "implement",
      "design",
      "develop",
      "construct",
      "generate",
      "deploy",
      "configure",
      "set up",
      "fix",
      "patch",
      // Chinese
      "构建",
      "创建",
      "实现",
      "设计",
      "开发",
      "生成",
      "部署",
      "配置",
      "设置",
      "修复",
      // Japanese
      "構築",
      "作成",
      "実装",
      "設計",
      "開発",
      "生成",
      "デプロイ",
      "設定",
      "修正",
      // Russian
      "построить",
      "построй",
      "создать",
      "создай",
      "реализовать",
      "реализуй",
      "спроектировать",
      "разработать",
      "разработай",
      "сконструировать",
      "сгенерировать",
      "сгенерируй",
      "развернуть",
      "разверни",
      "настроить",
      "настрой",
      "исправить",
      "исправь",
      // German
      "erstellen",
      "bauen",
      "implementieren",
      "entwerfen",
      "entwickeln",
      "konstruieren",
      "generieren",
      "bereitstellen",
      "konfigurieren",
      "einrichten",
      "beheben",
      // Spanish
      "construir",
      "crear",
      "implementar",
      "diseñar",
      "desarrollar",
      "generar",
      "desplegar",
      "configurar",
      "arreglar",
      // Portuguese
      "construir",
      "criar",
      "implementar",
      "projetar",
      "desenvolver",
      "gerar",
      "implantar",
      "configurar",
      "corrigir",
      // Korean
      "구축",
      "생성",
      "구현",
      "설계",
      "개발",
      "배포",
      "설정",
      "수정",
      // Arabic
      "بناء",
      "إنشاء",
      "تنفيذ",
      "تصميم",
      "تطوير",
      "توليد",
      "نشر",
      "إعداد",
      "أصلح"
    ],

    constraintIndicators: [
      // English
      "under",
      "at most",
      "at least",
      "within",
      "no more than",
      "o(",
      "maximum",
      "minimum",
      "limit",
      "budget",
      "must",
      "cannot",
      "without",
      "strict",
      "hard requirement",
      "zero external",
      "<1ms",
      // Chinese
      "不超过",
      "至少",
      "最多",
      "在内",
      "最大",
      "最小",
      "限制",
      "预算",
      "必须",
      "不能",
      "严格",
      "零外部",
      // Japanese
      "以下",
      "最大",
      "最小",
      "制限",
      "予算",
      "必須",
      "できない",
      "厳格",
      // Russian
      "не более",
      "не менее",
      "как минимум",
      "в пределах",
      "максимум",
      "минимум",
      "ограничение",
      "бюджет",
      "должен",
      "нельзя",
      "без",
      "строго",
      "жёсткое требование",
      "без внешних вызовов",
      // German
      "höchstens",
      "mindestens",
      "innerhalb",
      "nicht mehr als",
      "maximal",
      "minimal",
      "grenze",
      "budget",
      "muss",
      "darf nicht",
      "ohne",
      "streng",
      // Spanish
      "como máximo",
      "al menos",
      "dentro de",
      "no más de",
      "máximo",
      "mínimo",
      "límite",
      "presupuesto",
      "debe",
      "no puede",
      "sin",
      "estricto",
      // Portuguese
      "no máximo",
      "pelo menos",
      "dentro de",
      "não mais que",
      "máximo",
      "mínimo",
      "limite",
      "orçamento",
      "deve",
      "não pode",
      "sem",
      "estrito",
      // Korean
      "이하",
      "이상",
      "최대",
      "최소",
      "제한",
      "예산",
      "반드시",
      "할 수 없다",
      "없이",
      "엄격",
      // Arabic
      "على الأكثر",
      "على الأقل",
      "ضمن",
      "لا يزيد عن",
      "أقصى",
      "أدنى",
      "حد",
      "ميزانية",
      "يجب",
      "لا يمكن",
      "بدون",
      "صارم"
    ],

    outputFormatKeywords: [
      // English
      "json",
      "yaml",
      "xml",
      "table",
      "csv",
      "markdown",
      "schema",
      "format as",
      "structured",
      "diff",
      "patch",
      "typescript",
      "bash",
      "curl",
      // Chinese
      "表格",
      "格式化为",
      "结构化",
      "补丁",
      // Japanese
      "テーブル",
      "フォーマット",
      "構造化",
      "パッチ",
      // Russian
      "таблица",
      "форматировать как",
      "структурированный",
      "патч",
      // German
      "tabelle",
      "formatieren als",
      "strukturiert",
      "patch",
      // Spanish
      "tabla",
      "formatear como",
      "estructurado",
      "parche",
      // Portuguese
      "tabela",
      "formatar como",
      "estruturado",
      "patch",
      // Korean
      "테이블",
      "형식",
      "구조화",
      "패치",
      // Arabic
      "جدول",
      "تنسيق",
      "منظم",
      "تصحيح"
    ],

    referenceKeywords: [
      // English
      "above",
      "below",
      "previous",
      "following",
      "the docs",
      "the api",
      "the code",
      "earlier",
      "attached",
      "this repo",
      "thread",
      "conversation",
      // Chinese
      "上面",
      "下面",
      "之前",
      "接下来",
      "文档",
      "代码",
      "附件",
      "这个仓库",
      "线程",
      "对话",
      // Japanese
      "上記",
      "下記",
      "前の",
      "次の",
      "ドキュメント",
      "コード",
      "添付",
      "このリポジトリ",
      "スレッド",
      "会話",
      // Russian
      "выше",
      "ниже",
      "предыдущий",
      "следующий",
      "документация",
      "код",
      "ранее",
      "вложение",
      "этот репозиторий",
      "тред",
      "разговор",
      // German
      "oben",
      "unten",
      "vorherige",
      "folgende",
      "dokumentation",
      "der code",
      "früher",
      "anhang",
      "dieses repo",
      "thread",
      "gespräch",
      // Spanish
      "arriba",
      "abajo",
      "anterior",
      "siguiente",
      "documentación",
      "el código",
      "adjunto",
      "este repo",
      "hilo",
      "conversación",
      // Portuguese
      "acima",
      "abaixo",
      "anterior",
      "seguinte",
      "documentação",
      "o código",
      "anexo",
      "este repositório",
      "thread",
      "conversa",
      // Korean
      "위",
      "아래",
      "이전",
      "다음",
      "문서",
      "코드",
      "첨부",
      "이 저장소",
      "스레드",
      "대화",
      // Arabic
      "أعلاه",
      "أدناه",
      "السابق",
      "التالي",
      "الوثائق",
      "الكود",
      "مرفق",
      "هذا المستودع",
      "محادثة",
      "سلسلة"
    ],

    negationKeywords: [
      // English
      "don't",
      "do not",
      "avoid",
      "never",
      "without",
      "except",
      "exclude",
      "no longer",
      "rather than",
      "instead of",
      // Chinese
      "不要",
      "避免",
      "从不",
      "没有",
      "除了",
      "排除",
      "而不是",
      // Japanese
      "しないで",
      "避ける",
      "決して",
      "なしで",
      "除く",
      "ではなく",
      // Russian
      "не делай",
      "не надо",
      "нельзя",
      "избегать",
      "никогда",
      "без",
      "кроме",
      "исключить",
      "больше не",
      "вместо",
      // German
      "nicht",
      "vermeide",
      "niemals",
      "ohne",
      "außer",
      "ausschließen",
      "nicht mehr",
      "anstatt",
      // Spanish
      "no hagas",
      "evitar",
      "nunca",
      "sin",
      "excepto",
      "excluir",
      "en lugar de",
      // Portuguese
      "não faça",
      "evitar",
      "nunca",
      "sem",
      "exceto",
      "excluir",
      "em vez de",
      // Korean
      "하지 마",
      "피하다",
      "절대",
      "없이",
      "제외",
      "대신",
      // Arabic
      "لا تفعل",
      "تجنب",
      "أبداً",
      "بدون",
      "باستثناء",
      "استبعاد",
      "بدلاً من"
    ],

    domainSpecificKeywords: [
      // English
      "quantum",
      "fpga",
      "vlsi",
      "risc-v",
      "asic",
      "photonics",
      "genomics",
      "proteomics",
      "topological",
      "homomorphic",
      "zero-knowledge",
      "lattice-based",
      "openclaw",
      "bankr",
      "anthropic",
      "gemini",
      "qwen",
      "kimi",
      "gpt",
      "mcp",
      "ollama",
      "vllm",
      "llm gateway",
      // Chinese
      "量子",
      "光子学",
      "基因组学",
      "蛋白质组学",
      "拓扑",
      "同态",
      "零知识",
      "格密码",
      "上下文窗口",
      "工具调用",
      "网关",
      // Japanese
      "量子",
      "フォトニクス",
      "ゲノミクス",
      "トポロジカル",
      "コンテキストウィンドウ",
      "ツール呼び出し",
      "ゲートウェイ",
      // Russian
      "квантовый",
      "фотоника",
      "геномика",
      "протеомика",
      "топологический",
      "гомоморфный",
      "с нулевым разглашением",
      "на основе решёток",
      "контекстное окно",
      "вызов инструментов",
      "шлюз llm",
      // German
      "quanten",
      "photonik",
      "genomik",
      "proteomik",
      "topologisch",
      "homomorph",
      "zero-knowledge",
      "gitterbasiert",
      "kontextfenster",
      "tool-calling",
      "llm gateway",
      // Spanish
      "cuántico",
      "fotónica",
      "genómica",
      "proteómica",
      "topológico",
      "homomórfico",
      "ventana de contexto",
      "llamada de herramientas",
      "pasarela llm",
      // Portuguese
      "quântico",
      "fotônica",
      "genômica",
      "proteômica",
      "topológico",
      "homomórfico",
      "janela de contexto",
      "chamada de ferramentas",
      "gateway llm",
      // Korean
      "양자",
      "포토닉스",
      "유전체학",
      "위상",
      "동형",
      "컨텍스트 윈도우",
      "도구 호출",
      "llm 게이트웨이",
      // Arabic
      "كمي",
      "ضوئيات",
      "جينوميات",
      "طوبولوجي",
      "تماثلي",
      "نافذة السياق",
      "استدعاء الأدوات",
      "بوابة llm"
    ],

    agenticTaskKeywords: [
      // English
      "read file",
      "read the file",
      "look at",
      "check the",
      "open the",
      "edit",
      "modify",
      "update the",
      "change the",
      "write to",
      "create file",
      "execute",
      "deploy",
      "install",
      "npm",
      "pip",
      "compile",
      "after that",
      "and also",
      "once done",
      "step 1",
      "step 2",
      "fix",
      "debug",
      "until it works",
      "keep trying",
      "iterate",
      "make sure",
      "verify",
      "confirm",
      "wire up",
      "integrate",
      // Chinese
      "读取文件",
      "查看",
      "打开",
      "编辑",
      "修改",
      "更新",
      "创建",
      "执行",
      "部署",
      "安装",
      "第一步",
      "第二步",
      "修复",
      "调试",
      "直到",
      "确认",
      "验证",
      "集成",
      // Japanese
      "ファイルを読む",
      "開く",
      "編集",
      "修正",
      "更新",
      "作成",
      "実行",
      "デプロイ",
      "インストール",
      "ステップ1",
      "ステップ2",
      "デバッグ",
      "確認",
      "検証",
      "統合",
      // Russian
      "читать файл",
      "открой",
      "отредактируй",
      "измени",
      "обнови",
      "создай файл",
      "выполни",
      "разверни",
      "установи",
      "шаг 1",
      "шаг 2",
      "исправь",
      "отладь",
      "пока не заработает",
      "проверь",
      "подтверди",
      "интегрируй",
      // German
      "datei lesen",
      "öffne",
      "bearbeiten",
      "ändern",
      "aktualisieren",
      "datei erstellen",
      "ausführen",
      "deployen",
      "installieren",
      "schritt 1",
      "schritt 2",
      "debuggen",
      "überprüfen",
      "bestätigen",
      "integrieren",
      // Spanish
      "leer archivo",
      "abrir",
      "editar",
      "modificar",
      "actualizar",
      "crear archivo",
      "ejecutar",
      "desplegar",
      "instalar",
      "paso 1",
      "paso 2",
      "arreglar",
      "depurar",
      "verificar",
      "confirmar",
      "integrar",
      // Portuguese
      "ler arquivo",
      "abrir",
      "editar",
      "modificar",
      "atualizar",
      "criar arquivo",
      "executar",
      "implantar",
      "instalar",
      "passo 1",
      "passo 2",
      "corrigir",
      "depurar",
      "verificar",
      "confirmar",
      "integrar",
      // Korean
      "파일 읽기",
      "열기",
      "편집",
      "수정",
      "업데이트",
      "파일 생성",
      "실행",
      "배포",
      "설치",
      "단계 1",
      "단계 2",
      "디버그",
      "확인",
      "검증",
      "통합",
      // Arabic
      "قراءة ملف",
      "فتح",
      "تحرير",
      "تعديل",
      "تحديث",
      "إنشاء ملف",
      "تنفيذ",
      "نشر",
      "تثبيت",
      "الخطوة 1",
      "الخطوة 2",
      "إصلاح",
      "تصحيح",
      "تحقق",
      "تأكيد",
      "ادمج"
    ],

    dimensionWeights: {
      tokenCount: 0.08,
      codePresence: 0.15,
      reasoningMarkers: 0.18,
      technicalTerms: 0.10,
      creativeMarkers: 0.05,
      simpleIndicators: 0.02,
      multiStepPatterns: 0.12,
      questionComplexity: 0.05,
      imperativeVerbs: 0.03,
      constraintCount: 0.04,
      outputFormat: 0.03,
      referenceComplexity: 0.02,
      negationComplexity: 0.01,
      domainSpecificity: 0.02,
      agenticTask: 0.04
    },

    tierBoundaries: {
      simpleMedium: 0.05,
      mediumComplex: 0.15,
      complexReasoning: 0.25
    },

    confidenceSteepness: 12,
    confidenceThreshold: 0.7
  },

  tiers: {
    SIMPLE: {
      primary: "meta/llama-3.1-8b-instruct",
      fallback: [
        "mistralai/mistral-nemo-12b-instruct",
        "meta/llama-3.1-70b-instruct"
      ]
    },
    MEDIUM: {
      primary: "meta/llama-3.1-70b-instruct",
      fallback: [
        "meta/llama-3.1-405b-instruct",
        "mistralai/mixtral-8x22b-instruct-v0.1"
      ]
    },
    COMPLEX: {
      primary: "meta/llama-3.1-405b-instruct",
      fallback: [
        "mistralai/mixtral-8x22b-instruct-v0.1",
        "meta/llama-3.1-70b-instruct"
      ]
    },
    VISION: {
      primary: "meta/llama-3.2-90b-vision-instruct",
      fallback: [
        "meta/llama-3.2-11b-vision-instruct"
      ]
    },
    REASONING: {
      primary: "deepseek-ai/deepseek-r1",
      fallback: [
        "meta/llama-3.1-405b-instruct"
      ]
    }
  },
  overrides: {
    maxTokensForceComplex: 100000,
    structuredOutputMinTier: "MEDIUM",
    ambiguousDefaultTier: "MEDIUM",
    enableAgenticAuto: true
  }
};